# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:          # [osx]
  - '11.0'                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '14'                   # [osx]

gstreamer:                 # [unix]
- '1.24'                   # [unix]
gst_plugins_base:          # [unix]
- '1.24'                   # [unix]

# Using vs2022
c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
