context:
  version: "6.11.0"
  maj_min: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: qt6-multimedia
  version: ${{ version }}

source:
  url: https://download.qt.io/official_releases/qt/${{ maj_min }}/${{ version }}/submodules/qtmultimedia-everywhere-src-${{ version }}.tar.xz
  sha256: 90c4cac0a7a983b68d1b0873d0714e7873b9a493403fa8593e8a4eea3ea26040

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - perl
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make
    - if: linux
      then:
        - ruby
        - bison
        - flex
        - gperf
    - if: build_platform != target_platform
      then:
        - qt6-main ${{ version }}.*
        - ffmpeg
        - ffmpeg * lgpl*
        - if: linux
          then:
            - pulseaudio-client
            - xorg-libx11
            - xorg-libxext
            - xorg-libxdamage
            - xorg-libxrandr
            - xorg-libxcomposite
            - xorg-libxxf86vm
            - xorg-libxtst
            - xorg-xf86vidmodeproto
            - pulseaudio-client
  host:
    - qt6-main ${{ version }}.*
    - ffmpeg
    - ffmpeg * lgpl*
    - if: linux
      then:
        - pthread-stubs
        - pulseaudio-client
        - libgl-devel
        - libglx-devel
        - libegl-devel
        - libopengl-devel
        - xorg-libx11
        - xorg-libxext
        - xorg-libxdamage
        - xorg-libxrandr
        - xorg-libxcomposite
        # https://github.com/conda-forge/staged-recipes/pull/22084
        - xorg-libxxf86vm
        - xorg-libxtst
        - xorg-xf86vidmodeproto
        - alsa-lib
    - if: not osx
      then:
        - libvulkan-headers
        - libvulkan-loader
  run:
    - qt6-main ${{ version }}.*
    - if: linux
      then:
        - xorg-libx11
        - xorg-libxrandr
  run_exports:
    - ${{ pin_subpackage('qt6-multimedia', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then:
          - test -d $PREFIX/include/qt6/QtSpatialAudio
          - test -d $PREFIX/include/qt6/QtMultimedia
          - test -f $PREFIX/lib/libQt6Multimedia${SHLIB_EXT}
          - test -f $PREFIX/lib/qt6/plugins/multimedia/libffmpegmediaplugin${SHLIB_EXT}
        else:
          - if not exist %PREFIX%\\Library\\include\\qt6\\QtMultimedia exit 1
          - if not exist %PREFIX%\\Library\\lib\\Qt6Multimedia.lib exit 1
          - if not exist %PREFIX%\\Library\\bin\\Qt6Multimedia.dll exit 1
          - if not exist %PREFIX%\\Library\\lib\\qt6\\plugins\\multimedia\\ffmpegmediaplugin.dll exit 1

about:
  homepage: http://qt-project.org
  license: GPL-3.0-only
  license_file: LICENSES/GPL-3.0-only.txt
  summary: Qt is a cross-platform application and UI framework.
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  documentation: http://doc.qt.io/
  repository: https://github.com/qt/qtmultimedia

extra:
  recipe-maintainers:
    - mmcauliffe
    - conda-forge/qt-main
  feedstock-name: qt-multimedia
